name: OS-Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm gcc-multilib binutils make

      - name: Compile OS Image
        run: make

      - name: Upload OS Binary
        uses: actions/upload-artifact@v3
        with:
          name: Project-637-OS-v0.1
          path: os-image.bin
